name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-gh-pages:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-timechart-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-timechart-
            ${{ runner.os }}-npm-
      - run: npm ci
      - run: npm test
      - name: git commit
        run: |
          git add -f ./dist
          git config user.email "github-action@huww98.cn"
          git config user.name "GitHub Action"
          git commit -m "Build"
          git push -f origin HEAD:gh-pages
        env:
          CI: true
